version: '3.8'

services:
  product_stock_checker:
      image: ghcr.io/felixclements/product_stock_checker_js:main
      environment:
        - NODE_ENV=production
        - DB_HOST=db
        - DB_PORT=5432
        - DB_NAME=stockchecker
        - DB_USER=postgres
        - DB_PASSWORD=yourpassword
        - API_PORT=3000
      ports:
        - "3000:3000"
      depends_on:
        - db
      restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=stockchecker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: